name: blackout_dispatch
description: "Dispečerská aplikace pro nouzové jízdní řády při blackoutu"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  uuid: ^4.5.1
  csv: ^6.0.0
  intl: ^0.20.2
  collection: ^1.19.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gtfs/
